apiVersion: v1
kind: Service
metadata:
  name: {{.Values.webapi.name}}
  labels:
    service: {{.Values.webapi.name}}
spec:
  type: {{.Values.service.type}}
  selector:
    app: {{ .Values.webapi.name }}
  ports:
  - port: {{.Values.service.port}} #8000
    targetPort: {{.Values.service.targetPort}} #8000
    nodePort: {{.Values.service.nodePort}} #32453
