apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.webapi.name}}
  labels:
    name: {{ .Values.webapi.name}}
spec:
  replicas: {{ .Values.webapi.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.webapi.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.webapi.name }}
    spec:
      containers:
      - name: {{ .Values.webapi.name }}
        image: "{{ .Values.webapi.image.repository }}:{{ .Values.webapi.image.tag }}"
        ports:
        - name: https
          containerPort: {{ .Values.webapi.containerPort }}
        envFrom:
        - configMapRef:
            name: {{ .Values.webapi.name }}
        {{- if .Values.secrets.enabled }}
        - secretRef:
            name: {{ .Values.webapi.name }}
        {{- end}}
        {{- if .Values.webapi.probes.enabled}}
        readinessProbe:
          httpGet:
            path: {{ .Values.webapi.readinessProbe.path}}
            port: https
            scheme: {{ .Values.webapi.readinessProbe.scheme}}
          initialDelaySeconds: {{ .Values.webapi.readinessProbe.initialDelaySeconds}}
          periodSeconds: {{ .Values.webapi.readinessProbe.periodSeconds}}
        livenessProbe:
          httpGet:
            path: {{ .Values.webapi.livenessProbe.path}}
            port: https
            scheme: {{ .Values.webapi.livenessProbe.scheme}}
          initialDelaySeconds: {{ .Values.webapi.livenessProbe.initialDelaySeconds}}
          periodSeconds: {{ .Values.webapi.livenessProbe.periodSeconds}}
      {{- end}}
      imagePullSecrets:
        - name: regcred # this secret need to be on k8s master
      restartPolicy: Always
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 0
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 0
