{{- if .Values.secrets.enabled -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.webapi.name}}
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    {{- range $key, $val := .Values.secrets.secretValues }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
{{- end }}
